# GRPO Math Training Configuration
# Example configuration for training mathematical reasoning with GRPO

# Dataset configuration
datasets:
  - path: AmirMohseni/Big-Math-RL-filtered
    split: train

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
validation_datasets:
  - path: AmirMohseni/Big-Math-RL-filtered
    split: validation

# Field mapping configuration
# Maps dataset fields to expected question/answer format
field_mapping:
  question_field: question
  answer_field: answer_correct

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
# validation_field_mapping:
#   question_field: question
#   answer_field: answer_correct

# Model configuration  
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true

# Training configuration
output_dir: runs/qwen-2.5-3b
num_train_epochs: 1
max_steps: 1000
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
loss_type: "dr_grpo"
max_prompt_length: 512
max_completion_length: 2048
num_generations: 8
reward_weights: [0.2, 1.0] # [format w, accuracy w]

# VLLM configuration for fast generation
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.5

# Logging configuration
logging_strategy: steps
logging_steps: 10
save_strategy: steps
save_steps: 100
save_total_limit: 2

# Evaluation configuration (optional)
# Only used if validation datasets are provided
eval_strategy: steps
eval_steps: 50
eval_on_start: true
# Note: per_device_eval_batch_size is set above to match training batch size

# Script-specific arguments
dataset_seed: 42

# PEFT configuration
use_peft: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
lora_task_type: "CAUSAL_LM"
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj

# Reporting
report_to: 
  - wandb
run_name: grpo-qwen-2.5-3b-19-50-lora

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save
hub_model_id: AmirMohseni/grpo-qwen-2.5-3b
