# GRPO VLM Training Configuration
# Example configuration for training vision-language models with GRPO on mathematical reasoning

# Dataset configuration
datasets:
  - path: Osilly/Vision-R1-rl
    split: train

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
validation_datasets:
  - path: Osilly/Vision-R1-rl
    split: test[:5%]

# Field mapping configuration
# Maps dataset fields to expected question/answer/image format
field_mapping:
  question_field: problem
  answer_field: answer
  image_field: images

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
validation_field_mapping:
  question_field: problem
  answer_field: answer
  image_field: images

# Model configuration  
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
trust_remote_code: true  # Required for VLM models

# Training configuration
output_dir: runs/qwen2.5-vl-3b
num_train_epochs: 1
#max_steps: 1000
per_device_train_batch_size: 2  # Reduced for VLM due to image memory usage
per_device_eval_batch_size: 2   # Reduced for VLM due to image memory usage
gradient_accumulation_steps: 16  # Increased to maintain effective batch size
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
loss_type: "dr_grpo"
max_prompt_length: 1536  # Longer for multimodal prompts
max_completion_length: 3072
num_generations: 8
reward_weights: [0.2, 1.0] # [format w, accuracy w]

# VLLM configuration for fast generation
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.4

# Logging configuration
logging_strategy: steps
logging_steps: 5
save_strategy: steps
save_steps: 25
save_total_limit: 2

# Evaluation configuration (optional)
# Only used if validation datasets are provided
eval_strategy: steps
eval_steps: 10
eval_on_start: true
# Note: per_device_eval_batch_size is set above to match training batch size

# Script-specific arguments
dataset_seed: 42

# PEFT configuration - adjusted for VLM
# use_peft: true
# lora_r: 16
# lora_alpha: 32
# lora_dropout: 0.1
# lora_task_type: "CAUSAL_LM"
# lora_target_modules:
#   - q_proj
#   - k_proj
#   - v_proj
#   - o_proj
#   - gate_proj
#   - up_proj
#   - down_proj

# Reporting
report_to: 
  - wandb
run_name: grpo-qwen2.5-vl-3b-14-10

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save
hub_model_id: AmirMohseni/grpo-qwen2.5-vl-3b

# Additional VLM-specific optimizations
dataloader_num_workers: 2  # Moderate parallelism for image processing
dataloader_pin_memory: true
remove_unused_columns: false  # Keep all columns for multimodal data

