# GRPO Math Training Configuration
# Example configuration for training mathematical reasoning with GRPO

# Dataset configuration
datasets:
  - path: AmirMohseni/OneShot-RLVR
    split: train

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
validation_datasets:
  - path: HuggingFaceH4/aime_2024
    split: train

# Field mapping configuration
# Maps dataset fields to expected question/answer format
field_mapping:
  question_field: question
  answer_field: answer

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
validation_field_mapping:
  question_field: problem
  answer_field: answer

# Model configuration  
model_name_or_path: Qwen/Qwen2.5-Math-1.5B
model_revision: main
torch_dtype: bfloat16
#attn_implementation: flash_attention_2
bf16: true

# Training configuration
output_dir: runs/qwen-2.5-math-1.5b
num_train_epochs: 20
#max_steps: 1000
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
max_prompt_length: 512
max_completion_length: 3072
num_generations: 8

# VLLM configuration for fast generation
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.6

# Logging configuration
logging_strategy: steps
logging_steps: 1
save_strategy: steps
save_steps: 20
save_total_limit: 2

# Evaluation configuration (optional)
# Only used if validation datasets are provided
eval_strategy: steps
eval_steps: 10
eval_delay: 0
# Note: per_device_eval_batch_size is set above to match training batch size

# Script-specific arguments
dataset_seed: 42

# PEFT configuration
use_peft: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
lora_task_type: "CAUSAL_LM"
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj

# Reporting
report_to: 
  - wandb
run_name: grpo-qwen-2.5-math-1.5b-lora-13-10

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save
hub_model_id: AmirMohseni/qwen-2.5-math-1.5b-lora
