# GRPO Math Training Configuration
# Example configuration for training mathematical reasoning with GRPO

# Dataset configuration
datasets:
  - path: AmirMohseni/OneShot-RLVR
    split: train

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
validation_datasets:
  - path: math-ai/amc23
    split: test

# Field mapping configuration
# Maps dataset fields to expected question/answer format
field_mapping:
  question_field: question
  answer_field: answer

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
validation_field_mapping:
  question_field: question
  answer_field: answer

# Model configuration  
model_name_or_path: Qwen/Qwen2.5-Math-1.5B
model_revision: main
torch_dtype: bfloat16
#attn_implementation: flash_attention_2
bf16: true

# Training configuration
output_dir: runs/qwen-2.5-math-1.5b
#num_train_epochs: 20
max_steps: 1000
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-6
#lr_scheduler_type: cosine
#warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
loss_type: "dr_grpo"
max_prompt_length: 1024
max_completion_length: 3072
temperature: 0.6
num_generations: 8
reward_weights: [0.0, 1.0]

# VLLM configuration for fast generation
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.25

# Logging configuration
logging_strategy: steps
logging_steps: 5
logging_first_step: true
save_strategy: steps
save_steps: 25
save_total_limit: 2

# Evaluation configuration (optional)
# Only used if validation datasets are provided
eval_strategy: steps
eval_steps: 25
eval_delay: 5

# Script-specific arguments
dataset_seed: 42

# PEFT configuration
#use_peft: false
#lora_r: 16
#lora_alpha: 32
#lora_dropout: 0.1
#lora_task_type: "CAUSAL_LM"
#lora_target_modules:
#  - q_proj
#  - k_proj
#  - v_proj

# Reporting
report_to: 
  - wandb
run_name: grpo-qwen-2.5-math-1.5b-16-07

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save
hub_model_id: AmirMohseni/qwen-qwen-2.5-math-1.5b-pi13
