# GRPO Math Training Configuration
# Example configuration for training mathematical reasoning with GRPO

# Dataset configuration
datasets:
  - path: AmirMohseni/RLMF-Autocorrect-Dataset
    split: stem_train

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
validation_datasets:
  - path: AmirMohseni/RLMF-Autocorrect-Dataset
    split: stem_test[:50%]

# Field mapping configuration
# Maps dataset fields to expected question/answer format
field_mapping:
  question_field: question
  answer_field: correct_answer

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
validation_field_mapping:
  question_field: question
  answer_field: correct_answer

# Model configuration  
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true

# Training configuration
output_dir: runs/qwen2.5-7b
num_train_epochs: 1
#max_steps: 400
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-6
lr_scheduler_type: cosine
warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
loss_type: "dr_grpo"
max_prompt_length: 1536
max_completion_length: 1536
num_generations: 8
reward_weights: [0.1, 1.0] # [format w, accuracy w]

# VLLM configuration for fast generation
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.55

# Logging configuration
logging_strategy: steps
logging_steps: 1
save_strategy: steps
save_steps: 10
save_total_limit: 2
log_completions: true  # Log sample completions for debugging
num_completions_to_print: 3  # Number of completions to show

# Evaluation configuration (optional)
# Only used if validation datasets are provided
eval_strategy: steps
eval_steps: 10
eval_on_start: false
# Note: per_device_eval_batch_size is set above to match training batch size

# Script-specific arguments
dataset_seed: 42

# LLM Judge configuration for accuracy reward
use_llm_judge: true  # Set to false to use only math_verify (no LLM fallback)
llm_judge_model_name: gpt-5-nano
llm_judge_api_key_name: OPENAI_API_KEY
# llm_judge_base_url: null  # Optional: custom API endpoint
llm_judge_temperature: 0.0

# PEFT configuration
use_peft: true
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
lora_task_type: "CAUSAL_LM"
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj

# Reporting
report_to: 
  - wandb
run_name: grpo-qwen2.5-7b-12-22-lora
project_name: grpo-math-training

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save
hub_model_id: AmirMohseni/grpo-qwen2.5-7b-stem-lora
