# GRPO Math Training Configuration
# Example configuration for training mathematical reasoning with GRPO

# Dataset configuration
datasets:
  - path: skrishna/gsm8k_only_answer
    split: test

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
validation_datasets:
  - path: math-ai/amc23
    split: test

# Field mapping configuration
# Maps dataset fields to expected question/answer format
field_mapping:
  question_field: text
  answer_field: label

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
validation_field_mapping:
  question_field: question
  answer_field: answer

# Model configuration  
model_name_or_path: AmirMohseni/Qwen2.5-3b-gsm8k-cipher-merged
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true

# Training configuration
output_dir: runs/grpo-qwen2.5-3b-gsm8k-cipher-v2
#num_train_epochs: 20
max_steps: 200
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-4
lr_scheduler_type: constant
#warmup_ratio: 0.03

# GRPO specific parameters
beta: 0.001
loss_type: "dr_grpo"
max_prompt_length: 1536
max_completion_length: 3500
#temperature: 0.6
num_generations: 8
reward_weights: [0.0, 1.0]

# VLLM configuration for fast generation
use_vllm: true
vllm_mode: colocate
vllm_gpu_memory_utilization: 0.4

# Logging configuration
logging_strategy: steps
logging_steps: 1
logging_first_step: true
save_strategy: steps
save_steps: 25
save_total_limit: 2

# Evaluation configuration (optional)
# Only used if validation datasets are provided
eval_strategy: steps
eval_steps: 25
eval_on_start: false

# Script-specific arguments
dataset_seed: 42

# LLM Judge configuration for accuracy reward
use_llm_judge: true  # Set to false to use only math_verify (no LLM fallback)
llm_judge_model_name: gpt-5-nano
llm_judge_api_key_name: OPENAI_API_KEY
# llm_judge_base_url: null  # Optional: custom API endpoint
llm_judge_temperature: 0.0

# PEFT configuration
use_peft: true
lora_r: 4
lora_alpha: 8
lora_dropout: 0.1
lora_task_type: "CAUSAL_LM"
lora_target_modules: "all-linear"

# Reporting
report_to: 
  - wandb
run_name: qwen2.5-3b-gsm8k-cipher-grpo-v2
project_name: cipher-grpo-training

# Hugging Face Hub
push_to_hub: true
hub_strategy: every_save
hub_model_id: AmirMohseni/qwen2.5-3b-gsm8k-cipher-grpo-v2
