# SFT LoRA Training Configuration Example  
# This configuration demonstrates LoRA fine-tuning with the enhanced SFT script

# Model configuration
model_name_or_path: "Qwen/Qwen2.5-3B-Instruct"
trust_remote_code: true

# Dataset configuration
datasets:
  - path: "AmirMohseni/gsm8k-cipher-sft" 
    split: "train"

# Optional validation dataset configuration
# If provided, will be used for evaluation during training
#validation_datasets:
#  - path: "AmirMohseni/cipher-gsm8k"
#    split: "test"
    
# Training arguments optimized for LoRA
learning_rate: 1.0e-4  # Higher learning rate for LoRA
lr_scheduler_type: "constant"
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
max_length: 1024

# Evaluation
#eval_strategy: "steps"
#eval_steps: 50
#eval_on_start: true
#per_device_eval_batch_size: 2

# Logging and tracking  
logging_steps: 1
output_dir: "runs/qwen2.5-3b-gsm8k-cipher-lora-sft"
run_name: "sft-qwen2.5-3b-gsm8k-cipher-lora"
project_name: "cipher-sft-training" 
report_to: ["wandb"]

# LoRA configuration
use_peft: true
lora_r: 4
lora_alpha: 8
lora_dropout: 0.01
lora_target_modules: "all-linear"

# Quantization for memory efficiency
#load_in_8bit: false
#load_in_4bit: true

# Saving and pushing
save_strategy: "steps"
save_steps: 50
save_total_limit: 1
push_to_hub: true

# Field mapping - specify question and completion/response fields in your dataset
field_mapping:
  question_field: "question"
  completion_field: "answer"

# Optional validation field mapping configuration
# If not provided, will use the same mapping as training dataset
#validation_field_mapping:
#  question_field: "question"
#  completion_field: "answer"


# Advanced options
dataloader_pin_memory: false
dataloader_num_workers: 1
remove_unused_columns: false
